#!/usr/bin/env python3
"""发送 PyTorch 社区日报邮件。

通过 MX 服务器直接投递邮件。收件人、发件人、MX 服务器等配置
从 .env 文件读取（REPORT_TO_EMAIL, SMTP_MX_SERVERS 等）。

用法:
    python3 send_report_email.py                          # 发送今天的日报
    python3 send_report_email.py 2026-04-15               # 发送指定日期的日报
    python3 send_report_email.py /path/to/report.md       # 发送指定文件
"""

import os
import smtplib
import socket
import sys
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

# ── 加载 .env ───────────────────────────────────────────
_env_file = Path(__file__).parent / ".env"
if _env_file.is_file():
    for line in _env_file.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, v = line.split("=", 1)
            os.environ.setdefault(k.strip(), v.strip())

# ── 配置（从环境变量读取）─────────────────────────────────
TO_ADDR = os.environ.get("REPORT_TO_EMAIL", "")
FROM_ADDR = os.environ.get("REPORT_FROM_EMAIL", f"pytorch-report@{socket.getfqdn()}")
REPORT_DIR = Path(__file__).parent / "reports"

MX_SERVERS = [s.strip() for s in os.environ.get("SMTP_MX_SERVERS", "").split(",") if s.strip()]
SMTP_PORT = int(os.environ.get("SMTP_PORT", "25"))
SMTP_TIMEOUT = int(os.environ.get("SMTP_TIMEOUT", "30"))
# ────────────────────────────────────────────────────────


def resolve_report_file(arg: str | None) -> Path:
    """根据参数找到要发送的报告文件。"""
    if arg is None:
        # 默认今天
        today = date.today().isoformat()
        return REPORT_DIR / f"pytorch_daily_{today}.md"
    if Path(arg).is_file():
        return Path(arg)
    # 当作日期解析
    return REPORT_DIR / f"pytorch_daily_{arg}.md"


def md_to_html(md_text: str) -> str:
    """将 Markdown 转为简单 HTML（用于邮件正文）。"""
    # 不再做复杂转换，直接将 markdown 文本包裹在 <pre> 中以保留原始格式
    import re
    # 转义 HTML 特殊字符
    html = md_text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    # 将 markdown 链接转为 HTML 链接: [text](url) -> <a href="url">text</a>
    html = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', html)
    # 粗体
    html = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", html)
    # 标题
    html = re.sub(r"^### (.+)$", r"<h3>\1</h3>", html, flags=re.MULTILINE)
    html = re.sub(r"^## (.+)$", r"<h2>\1</h2>", html, flags=re.MULTILINE)
    html = re.sub(r"^# (.+)$", r"<h1>\1</h1>", html, flags=re.MULTILINE)
    # 水平线
    html = re.sub(r"^---+$", "<hr>", html, flags=re.MULTILINE)
    # 列表项
    html = re.sub(r"^- (.+)$", r"<li>\1</li>", html, flags=re.MULTILINE)
    # 引用块
    html = re.sub(r"^> (.+)$", r"<blockquote>\1</blockquote>", html, flags=re.MULTILINE)
    # 段落换行
    html = html.replace("\n\n", "</p>\n<p>").replace("\n", "<br>\n")
    return f"<p>{html}</p>"


def extract_title(md_text: str) -> str:
    """从报告中提取标题作为邮件主题。"""
    for line in md_text.splitlines():
        stripped = line.strip()
        if stripped.startswith("# "):
            return stripped.lstrip("# ").strip()
    return "PyTorch 社区日报"


def build_email(report_path: Path) -> MIMEMultipart:
    """构造邮件对象。"""
    md_text = report_path.read_text(encoding="utf-8")
    subject = extract_title(md_text)
    html_body = md_to_html(md_text)

    msg = MIMEMultipart("alternative")
    msg["From"] = FROM_ADDR
    msg["To"] = TO_ADDR
    msg["Subject"] = subject

    # 纯文本版本
    msg.attach(MIMEText(md_text, "plain", "utf-8"))
    # HTML 版本
    html_full = f"""\
<html>
<head><meta charset="utf-8">
<style>
li {{ margin: 3px 0; }}
h1, h2, h3 {{ margin: 16px 0 8px 0; }}
blockquote {{ color: #57606a; margin: 8px 0; padding: 0 12px; border-left: 3px solid #d0d7de; }}
hr {{ border: none; border-top: 1px solid #d0d7de; margin: 16px 0; }}
</style>
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; color: #24292e;">
{html_body}
<hr style="margin-top: 40px; border: none; border-top: 1px solid #e1e4e8;">
<p style="color: #6a737d; font-size: 12px;">Auto-generated by PyTorchInsight</p>
</body>
</html>"""
    msg.attach(MIMEText(html_full, "html", "utf-8"))
    return msg


def send_via_mx(msg: MIMEMultipart) -> bool:
    """通过 MX 服务器直接投递邮件。"""
    for mx in MX_SERVERS:
        try:
            print(f"  连接 {mx}:{SMTP_PORT} ...")
            with smtplib.SMTP(mx, SMTP_PORT, timeout=SMTP_TIMEOUT) as smtp:
                smtp.ehlo(socket.getfqdn())
                recipients = [a.strip() for a in TO_ADDR.split(",") if a.strip()]
                smtp.sendmail(FROM_ADDR, recipients, msg.as_string())
                print(f"  ✓ 通过 {mx} 发送成功")
                return True
        except Exception as e:
            print(f"  ✗ {mx} 失败: {e}")
    return False


def main():
    global TO_ADDR

    # Parse arguments: [report_file] [--prod] [--to addr]
    args = sys.argv[1:]
    report_arg = None
    i = 0
    while i < len(args):
        if args[i] == "--prod":
            TO_ADDR = os.environ.get("REPORT_TO_EMAIL_PROD", TO_ADDR)
        elif args[i] == "--to" and i + 1 < len(args):
            i += 1
            TO_ADDR = args[i]
        elif not args[i].startswith("--"):
            report_arg = args[i]
        i += 1

    report_path = resolve_report_file(report_arg)

    if not TO_ADDR:
        print("错误: 未配置 REPORT_TO_EMAIL，请在 .env 中设置")
        sys.exit(1)
    if not MX_SERVERS:
        print("错误: 未配置 SMTP_MX_SERVERS，请在 .env 中设置")
        sys.exit(1)

    if not report_path.is_file():
        print(f"报告文件不存在: {report_path}")
        sys.exit(1)

    print(f"发送报告: {report_path}")
    print(f"收件人:   {TO_ADDR}")

    msg = build_email(report_path)
    print(f"主题:     {msg['Subject']}")

    if send_via_mx(msg):
        print("邮件发送完成!")
    else:
        print("所有 MX 服务器均失败，邮件未发送。")
        sys.exit(1)


if __name__ == "__main__":
    main()
